definitions:
  models.Course:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      modules:
        items:
          $ref: '#/definitions/models.Module'
        type: array
      title:
        type: string
      updated_at:
        type: string
    required:
    - title
    type: object
  models.Lesson:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      module_id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Module:
    properties:
      content:
        description: Penjelasan isi modul, bisa teks, HTML, dll.
        type: string
      course_id:
        description: Foreign key untuk relasi ke Course
        type: integer
      created_at:
        type: string
      id:
        type: integer
      lessons:
        description: Relasi one-to-many ke Lesson
        items:
          $ref: '#/definitions/models.Lesson'
        type: array
      title:
        description: Judul modul, wajib diisi
        type: string
      updated_at:
        type: string
    required:
    - title
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /courses:
    post:
      consumes:
      - application/json
      description: Create a new course and save it to the database
      parameters:
      - description: Course to create
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/models.Course'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Course'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new course
      tags:
      - courses
  /courses/:
    get:
      description: Retrieve all the courses from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Course'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all courses
      tags:
      - courses
  /courses/{id}:
    delete:
      description: Delete a course from the database by its ID
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a course by ID
      tags:
      - courses
    get:
      consumes:
      - application/json
      description: Retrieve a course by its ID from the database
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Course'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a course by ID
      tags:
      - courses
    put:
      consumes:
      - application/json
      description: Update the details of a course by its ID
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: string
      - description: Course to update
        in: body
        name: course
        required: true
        schema:
          $ref: '#/definitions/models.Course'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Course'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an existing course
      tags:
      - courses
swagger: "2.0"
